### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [reckyy/Be_Notioner#118]
お疲れ様です。
まずはMattermostに投稿いただいていた以下に関して回答します。

> チュートリアルページについて
なるべくNotionの世界観(?)を大事にしようと思っているので、チュートリアルもNotionのページを作成し、それを埋め込もうと考えています。。ですが、それはテンプレートページと作業が同じなので技術的には＋0なので不安です（上記の悩みに帰結します。）。

このサービス触れましたが、何をしたいサービスなのかがハッキリしないように感じました。ショートカットキー一覧掲載サービスであれば、Notionで作成してそれを公開しても良いのではと感じてしまったので、そもそもこのサービスは何をユーザーに提供しているのかを一度考え直してみると良いかもしれません。

<br />

下記の観点でMVPレビュー行いました。

1. 就活において十分な技術力を示せる機能を実装しているか
2. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

### １について
まずはREADMEに書かれている「解決方法」を満たせているかの観点からレビューしました。

・「一つチュートリアルを作成することで、何からしたらいいかわからない人への登竜門になる。」とありましたが、ユーザーはどのようにチュートリアルを体験できるのかが分からなかったです。

・「Notionのいわゆる掲示板的なアプリにすることで、「これわからない」ということがあっても記事や質問欄などの活用で、（Notionと同じように）一つのサイトで完結できる。」の部分を必要性を感じなくなっているとのことですが、現状このサービスを他者に説明する際に、どんなサービスと説明できそうでしょうか。

次に技術面の観点からレビューしました。

・ユーザー登録・プロフィール登録・ログイン機能確認しました。違和感ない操作は良かったかと思います。ただ「なぜこれらの操作をするのだろう？」というのが気になりました。ログインしなければ使えない機能も無いようですし、プロフィール（名前やアイコンなど）を他のユーザーが目にする場所も無いのが気になりました。

・技術面ですが、厳しい印象を受けました。ショートカットキーの部分もHTMLで作れてしまうかと思いました。アピールできる部分（Google Apps ScriptとNotion APIを用いてGoogle Form投稿時に自動的にNotionテンプレートページにアクセスする）は良いかと思いますが、ユーザー体験から見るとアピール部分は少ない印象を受けました。

・shortcutsテーブルがありますが、app/views/shortcuts/index.html.erbを見ると直書きしているようなので、このテーブルは何を保存するテーブルなのだろうと気になりました。

<br />

### ２について
- 質問（実装しないなら非表示にしましょう）
- 記事（実装しないなら非表示にしましょう）
- プロフィール：ユーザー登録・ログイン機能・プロフィールに共通ですが、「なぜ登録・ログイン・プロフィールするのだろう？」と感じました。
- チュートリアル：遷移先で何ができるのかが分からず戸惑いました。
- テンプレート：テンプレート投稿部分の説明がもっと分かりやすくした方がよいかもと感じました。

<br />

技術的アピールという点では以下の機能などを追加する検討をすると良いと思います。また、このサービスを利用する利点などを感じづらかったので、どんなサービス・機能を提供したいかを一度考えてみましょう。

■チャット
・概要
FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
・使用技術・ライブラリ
- WebSocket：https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）：https://railsguides.jp/action_cable_overview.html

■ステップ入力・確認画面
・概要
1つのフォームで入力するには項目が多すぎる場合や、ユーザーの離脱を抑制するために、フォームを複数のステップに分割して入力できるようにすることがあります。また、1つのフォームで入力する場合でも、投稿後に編集できない情報がある場合には、確認画面を挟むことでユーザーに注意を促すなど、登録フォームのユーザビリティを考慮した様々な工夫が必要です。

**Comment by reckyy** [comment]
ご連絡ありがとうございます。
以下、ご回答になります。
***

> このサービス触れましたが、何をしたいサービスなのかがハッキリしないように感じました。ショートカットキー一覧掲載サービスであれば、Notionで作成してそれを公開しても良いのではと感じてしまったので、そもそもこのサービスは何をユーザーに提供しているのかを一度考え直してみると良いかもしれません。

一番は、「Notionは真っ白なページから始まる分、何から手をつけていいかわからない」ため、まずはNotionを使い始めて欲しいと思い作ったサービスです。
そのため、現時点でのメイン機能はテンプレート機能です。テンプレート一覧から自分の使いたいものを見つけ、「まずはNotionを使い始める」という状態に持っていくためです。（細かい機能はさておき）回答になっていますでしょうか。
ショートカットページに関してはご指摘の通りだと思います。（ショートカットはおまけのつもりでした、なので、別途ページに誘導するのではなく、Topページに掲載してもいいかなとも思いました。）

> ・「一つチュートリアルを作成することで、何からしたらいいかわからない人への登竜門になる。」とありましたが、ユーザーはどのようにチュートリアルを体験できるのかが分からなかったです。

こちらに関しては未実装で、悩んでる途中です。一応、アカウント登録から画面構成、ページ、ブロック、データベースこれらの作成方法などを解説した（画像付きで）作成しようかなと思っていました。Mattermostの方にご相談として記述していましたので、再度共有させていただきます。
（2. チュートリアルページについて
なるべくNotionの世界観(?)を大事にしようと思っているので、チュートリアルもNotionのページを作成し、それを埋め込もうと考えています。。ですが、それはテンプレートページと作業が同じなので技術的には＋0なので不安です（上記の悩みに帰結します。）

> ・「Notionのいわゆる掲示板的なアプリにすることで、「これわからない」ということがあっても記事や質問欄などの活用で、（Notionと同じように）一つのサイトで完結できる。」の部分を必要性を感じなくなっているとのことですが、現状このサービスを他者に説明する際に、どんなサービスと説明できそうでしょうか。

まずはNotionを使い始める、そのスイッチを押すサービスと現状では考えています。（初期とはコンセプトが変わってしまっています。。）

> ・ユーザー登録・プロフィール登録・ログイン機能確認しました。違和感ない操作は良かったかと思います。ただ「なぜこれらの操作をするのだろう？」というのが気になりました。ログインしなければ使えない機能も無いようですし、プロフィール（名前やアイコンなど）を他のユーザーが目にする場所も無いのが気になりました。

一応、未ログインユーザーがテンプレートページに飛ぶと、管理者（私）が投稿したテンプレートしか見れないようになっています。ログインすると、管理者以外が投稿したテンプレートも閲覧可能になります。
プロフィールの必要性（他のユーザーを目にする場所がないため）は私も気にしていました。なので、土屋様にご提示いただいたチャット機能を実装することで、テンプレートを投稿する際作成者欄にBe Noioner内のアカウント名を書いていただき、テンプレートの使い方など、何か質問があるときはユーザーを検索しチャットで質問できるようにするのはいいかなと今考えました。

> ・技術面ですが、厳しい印象を受けました。ショートカットキーの部分もHTMLで作れてしまうかと思いました。アピールできる部分（Google Apps ScriptとNotion APIを用いてGoogle Form投稿時に自動的にNotionテンプレートページにアクセスする）は良いかと思いますが、ユーザー体験から見るとアピール部分は少ない印象を受けました。

そうですよね、、ペインを解消する思いが先行してしまいました。

> ・shortcutsテーブルがありますが、app/views/shortcuts/index.html.erbを見ると直書きしているようなので、このテーブルは何を保存するテーブルなのだろうと気になりました。

こちらに関しては当方のミスで最初作成したまま放置しているものとなります。誤解を招いてしまい申し訳ございません。

**Comment by Tsuchiya2** [comment]
上記拝読しました。

・現状のアプリでは**就活は厳しい**

その上でこのサービスで何を提供したいのかを説明いただけますでしょうか？（上記の記載ではよく分からなかったため）
概要と合わせて具体的にどんな機能を実装するのかをお聞きしたいです。

**Comment by reckyy** [comment]
文章が煩雑で申し訳ございません。

**概要**
---
Notionを使いたいけど、使っていない人に`Notionを使い始めるきっかけ` を提供したいです。なので、まずは一番考えるのが面倒な、雛形のテンプレートを使っていただくことできっかけを作れるかなと思いました。
（ですが、「今考えるとNotionを使いたい人」にテンプレートを使って欲しいのに、Notionのテンプレートの投稿をお願いするのは「現在Notionを使用しているユーザー」なので、訪れるユーザーの想定に乖離が生じていることに気づきました。。この点も何がしたいサービスかわからないという点につながっているのかもしれません。）

**実装したい機能**
---
- チュートリアルページ
Notionのアカウント登録から画面構成、ページ、ブロック、データベースこれらの作成方法などを解説した（画像付きで）ページ（Notionで作成し、埋め込み）。

以下、今考えた機能になりますので、煮詰まっていない部分があります。
- チャット機能、ユーザー検索機能
（テンプレートのContributor（投稿者）のカラムに、Be Notionerに登録しているユーザー名と同じ名前を入力いただくことが前提）
ユーザーを検索し、テンプレートの使い方や交流に用いてもらう。

- Youtube API、Zenn API、Qiita APIを用いて「Notion」というキーワードが含まれた動画、記事のみを取得しリスト形式で表示する。記事へのブックマーク機能も実装し、Notionの情報収集に特化したアプリにする。この機能を実装することで、Notionをまだ使ったことがない方だけでなく、使っているユーザーも誘致できるかなと思いました。
（今調べたら、Youtubeとqiitaはできそうです）
表示形式はZennのように、Youtube、Qiita、Zennと分けて表示する。（以下の画像で言うと、Trending = Youtube、Following = Qiita、といった具合にです。
![イメージ](https://i.gyazo.com/d6a7052fa98ed5fa01985ae9fb916333.png)

上記のアイデアについて、ご意見いただけますと幸いです。よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
以下コメントになります。

---

> チュートリアルページ
Notionのアカウント登録から画面構成、ページ、ブロック、データベースこれらの作成方法などを解説した（画像付きで）ページ（Notionで作成し、埋め込み）。

上記部分ですが、Notionで作成したものをこのサービス上に埋め込み表示するということでしょうか？サービスとしての機能であれば良いかと思います。

<br /><br />

> チャット機能、ユーザー検索機能

こちらも漠然としている印象を受けました。テンプレートを提供したユーザーを検索して、テンプレートの使い方や交流に用いるとありますが、それならテンプレートの掲示板のようなものを用意して、そこにコメント（チャット機能）を施した方が、検索する手間も無くなるかと思いますが。。。いかがでしょうか。

<br /><br />

> Youtube API、Zenn API、Qiita APIを用いて「Notion」というキーワードが含まれた動画、記事のみを取得しリスト形式で表示する。記事へのブックマーク機能も実装し、Notionの情報収集に特化したアプリにする。この機能を実装することで、Notionをまだ使ったことがない方だけでなく、使っているユーザーも誘致できるかなと思いました。

こちらのアイディアは良いと思います。

<br /><br />

上記踏まえた上でのレビューとしては、サービス面はだいぶ解消されそうな印象です。技術面はチャット機能の部分がリアルタイム通信になればアピールポイントになるかと思います。ただデータベースを使用している箇所が少ない（ショートカットキーもデータベースを介していないetc）ので、以下の開発を行って就活に望むと良いかもしれません。

- Notion関係のリソース一覧表示
- Notion関係のリソース詳細表示
- Notion関係のリソース詳細表示画面でのリアルタイム通信でのコメント投稿機能
- チュートリアル機能（実装するか・削除するかの判断はお任せします）
- MVPリリース（2週間後締め切り）

上記リリース後、就活と並行して以下の機能実装を実装及びユーザーからのフィードバックを取捨選択して改善・反映させていってください。

- レコメンド機能：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
- 使用技術・ライブラリ
  - Amazon Personalize
    - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
    - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
  - GCP Recommendations AI
    - https://cloud.google.com/recommendations?hl=ja
    - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
  - アルゴリズム
    - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

---

以上がレビュー結果になります。
実装頑張ってください。

**Comment by reckyy** [comment]
返信ありがとうございます。
質問がございます。

---

> MVPリリース（2週間後締め切り）

と記載されていますが**2点**質問がございます。
- 今回はMVPリリースとしては認められず次回のMVPリリースも再度レビュー依頼をする形になるのでしょうか。
- また、締切に間に合わなかった場合はどうなるのでしょうか。間に合わなかった場合もその時点でMVPリリースする、ということでしょうか。

> こちらも漠然としている印象を受けました。テンプレートを提供したユーザーを検索して、テンプレートの使い方や交流に用いるとありますが、それならテンプレートの掲示板のようなものを用意して、そこにコメント（チャット機能）を施した方が、検索する手間も無くなるかと思いますが。。。いかがでしょうか。

確かにそうだと思います。現在のテンプレートページのNotion埋め込みを削除し、新たにHTMLを記述＆テンプレートのDBを作成し、表示すると言うことですね。（もし認識が誤っていたらご教授ください。）

よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
そうですね。MVPリリースレビューとしてはLGTMを出せない状態です。
そのため再度レビュー依頼をお願いいたします。

また、締切はあくまでも目安ですので、あまり長引かないように開発をお願いいたします。
（間に合わなかった場合を今考えるよりも、まずはそれに向けて頑張ってみてください。）

**Comment by reckyy** [comment]
返信ありがとうございます。
畏まりました。

尋ねさせて頂いた意図としては、卒業後三ヶ月以内にMVPリリースしないと、就職活動サポートを受けられないとのことでしたので尋ねさせて頂きました。
こちらの件に関しては、別途CTの方に尋ねさせて頂きます。
